# Generated by Django 4.1.2 on 2022-10-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('first_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('content', models.TextField(primary_key=True, serialize=False)),
                ('song_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('date_released', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('artist_id', models.IntegerField()),
            ],
        ),
    ]
